name: lemberfpsmonitor
version: 0.0.3+2
homepage: https://github.com/lember-ecu/fpsmonitoring

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

description:
  Flutter FPS Monitor is a package for monitoring FPS (Frames Per Second) performance in Flutter applications. This package provides developers with the opportunity to visually track and improve application performance. You can monitor FPS values in real-time, analyze application performance, and identify potential performance issues. By using advanced charts and data tables, you can examine FPS trends and changes, ensuring that your animations run smoothly. This package empowers Flutter developers to optimize application performance and enhance the user experience.